import type { SpeedUnit } from './speed-unit'
import { SPEED_UNIT } from './speed-unit';

const METER_PER_SECOND = 1;
const KILOMETER_PER_HOUR = METER_PER_SECOND / 3.6; 
const MILE_PER_HOUR = 0.44704 * METER_PER_SECOND; 
const KNOT = 0.514444 * METER_PER_SECOND; 
const FOOT_PER_SECOND = 0.3048 * METER_PER_SECOND; 
const INCH_PER_HOUR = 0.0000070556 * METER_PER_SECOND; 
const MILLIMETER_PER_HOUR = 0.000000277778 * METER_PER_SECOND; 

export const speedScale: Record<SpeedUnit, number> = {
  [SPEED_UNIT.METER_PER_SECOND]: METER_PER_SECOND,
  [SPEED_UNIT.KILOMETER_PER_HOUR]: KILOMETER_PER_HOUR,
  [SPEED_UNIT.MILE_PER_HOUR]: MILE_PER_HOUR,
  [SPEED_UNIT.KNOT]: KNOT,
  [SPEED_UNIT.FOOT_PER_SECOND]: FOOT_PER_SECOND,
  [SPEED_UNIT.INCH_PER_HOUR]: INCH_PER_HOUR,
  [SPEED_UNIT.MILLIMETER_PER_HOUR]: MILLIMETER_PER_HOUR,
};
