import type { AreaUnit } from './area-unit'
import { AREA_UNIT } from './area-unit';

const SQUARE_MILLIMETER = 1;
const SQUARE_CENTIMETER = 100 * SQUARE_MILLIMETER; 
const SQUARE_METER = 10_000 * SQUARE_CENTIMETER; 
const HECTARE = 10_000 * SQUARE_METER; 
const SQUARE_KILOMETER = 1_000_000 * SQUARE_METER; 

const SQUARE_INCH = 645.16 * SQUARE_MILLIMETER; 
const SQUARE_FOOT = 144 * SQUARE_INCH; 
const ACRE = 43_560 * SQUARE_FOOT; 
const SQUARE_MILE = 640 * ACRE; 

export const areaScale: Record<AreaUnit, number> = {
  [AREA_UNIT.SQUARE_MILLIMETER]: SQUARE_MILLIMETER,
  [AREA_UNIT.SQUARE_CENTIMETER]: SQUARE_CENTIMETER,
  [AREA_UNIT.SQUARE_METER]: SQUARE_METER,
  [AREA_UNIT.HECTARE]: HECTARE,
  [AREA_UNIT.SQUARE_KILOMETER]: SQUARE_KILOMETER,
  [AREA_UNIT.SQUARE_INCH]: SQUARE_INCH,
  [AREA_UNIT.SQUARE_FOOT]: SQUARE_FOOT,
  [AREA_UNIT.ACRE]: ACRE,
  [AREA_UNIT.SQUARE_MILE]: SQUARE_MILE,
};
