import type { VolumeUnit } from './volume-unit'
import { VOLUME_UNIT } from './volume-unit';

const CUBIC_MILLIMETER = 1;
const CUBIC_CENTIMETER = 1_000 * CUBIC_MILLIMETER; 
const CUBIC_METER = 1_000_000 * CUBIC_CENTIMETER; 
const CUBIC_KILOMETER = 1_000_000_000 * CUBIC_METER; 

const MILLILITER = CUBIC_CENTIMETER; 
const LITER = 1_000 * MILLILITER; 
const KILOLITER = 1_000 * LITER; 
const MEGALITER = 1_000 * KILOLITER; 
const GIGALITER = 1_000 * MEGALITER; 

const CUBIC_INCH = 16.387064 * CUBIC_CENTIMETER; 
const CUBIC_FOOT = 1_728 * CUBIC_INCH; 
const CUBIC_YARD = 27 * CUBIC_FOOT; 

const TEASPOON = 4.92892159375 * MILLILITER; 
const TABLESPOON = 3 * TEASPOON; 
const FLUID_OUNCE = 2 * TABLESPOON; 
const CUP = 8 * FLUID_OUNCE; 
const PINT = 2 * CUP; 
const QUART = 2 * PINT; 
const GALLON = 4 * QUART; 

export const volumeScale: Record<VolumeUnit, number> = {
  [VOLUME_UNIT.CUBIC_MILLIMETER]: CUBIC_MILLIMETER,
  [VOLUME_UNIT.CUBIC_CENTIMETER]: CUBIC_CENTIMETER,
  [VOLUME_UNIT.MILLILITER]: MILLILITER,
  [VOLUME_UNIT.LITER]: LITER,
  [VOLUME_UNIT.KILOLITER]: KILOLITER,
  [VOLUME_UNIT.MEGALITER]: MEGALITER,
  [VOLUME_UNIT.GIGALITER]: GIGALITER,
  [VOLUME_UNIT.CUBIC_METER]: CUBIC_METER,
  [VOLUME_UNIT.CUBIC_KILOMETER]: CUBIC_KILOMETER,
  [VOLUME_UNIT.TEASPOON]: TEASPOON,
  [VOLUME_UNIT.TABLESPOON]: TABLESPOON,
  [VOLUME_UNIT.CUBIC_INCH]: CUBIC_INCH,
  [VOLUME_UNIT.FLUID_OUNCE]: FLUID_OUNCE,
  [VOLUME_UNIT.CUP]: CUP,
  [VOLUME_UNIT.PINT]: PINT,
  [VOLUME_UNIT.QUART]: QUART,
  [VOLUME_UNIT.GALLON]: GALLON,
  [VOLUME_UNIT.CUBIC_FOOT]: CUBIC_FOOT,
  [VOLUME_UNIT.CUBIC_YARD]: CUBIC_YARD,
};
