import type { LengthUnit } from './length-unit'
import { LENGTH_UNIT } from './length-unit';

const NANOMETER = 1;
const MICROMETER = 1_000 * NANOMETER;
const MILLIMETER = 1_000 * MICROMETER;
const CENTIMETER = 10 * MILLIMETER;
const METER = 100 * CENTIMETER;
const KILOMETER = 1_000 * METER;

const INCH = 25.4 * MILLIMETER;
const FOOT = 12 * INCH;
const YARD = 3 * FOOT;
const MILE = 1609.344 * METER;

export const lengthScale: Record<LengthUnit, number> = {
  [LENGTH_UNIT.NANOMETER]: NANOMETER,
  [LENGTH_UNIT.MICROMETER]: MICROMETER,
  [LENGTH_UNIT.MILLIMETER]: MILLIMETER,
  [LENGTH_UNIT.CENTIMETER]: CENTIMETER,
  [LENGTH_UNIT.METER]: METER,
  [LENGTH_UNIT.KILOMETER]: KILOMETER,
  [LENGTH_UNIT.YARD]: YARD,
  [LENGTH_UNIT.FOOT]: FOOT,
  [LENGTH_UNIT.INCH]: INCH,
  [LENGTH_UNIT.MILE]: MILE,
};
